version: '3.8'

services:
  evo2:
    build: .
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ./hf_cache:/root/.cache/huggingface
      - ./data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]